### PR TITLE
fix: TeamMemberCard link doesn't extend to the whole element

### LINKED ISSUE #223: TeamMemberCard link doesn't extend to the whole element
Linked is only name. This can appear to be a bit strange - whole _button_ appears as clickable, but only name can be clicked.

### PR DESCRIPTION
**Pull request by Vallayah**
Closes #223

### CODE REVIEW

File: frontend/src/components/TeamMemberCard.jsx [hunk 1]
```diff
@@ -1,20 +1,31 @@
+import React from 'react';
```
Comment (gikf) [inline frontend/src/components/TeamMemberCard.jsx:1]: This is not needed.

**Review by gikf — APPROVED** [review]
