### PR TITLE
fix: remove '!isValid' argument from the button in 'RegisterForm

### LINKED ISSUE #195: Remove '!isValid' argument from the button in 'RegisterForm'
The Register form won't let you send your registration data unless all the fields are correctly filled in.
It will also show you a warning if the field is incorrectly, like the 'Password needs to be at least 8 characters long' one ...but only after you tried to send the form.
There's probably a way to let the user know the password must be of certain length while they're filling out the form, but allowing the user to try to send an invalid form is probably the easiest solution for now

### PR DESCRIPTION
**Pull request by Vallayah**
Closes #195

### CODE REVIEW

File: frontend/src/components/RegisterForm.jsx [hunk 1]
```diff
@@ -86,7 +87,12 @@ export function RegisterForm({ redirect_to = '/' }) {
   };
 
   return (
-    <form ref={formRef} onSubmit={handleSubmit(onSubmit)}>
+    <form
+      noValidate
```
Comment (gikf) [inline frontend/src/components/RegisterForm.jsx:91]: With other changes is this one required?

Comment (Vallayah) [reply frontend/src/components/RegisterForm.jsx:91]: I was fighting with Linter and tried a few solutions.😔

**Review by Vallayah — COMMENTED** [review]
done

**Review by gikf — APPROVED** [review]
